-- Insert sample resources with proper UUIDs
INSERT INTO public.resources (id, title, description, category, type, url, featured, difficulty, resources, tags) VALUES
('550e8400-e29b-41d4-a716-446655440001', 'Complete Web Development Bootcamp', 'Learn HTML, CSS, JavaScript, React, Node.js and more in this comprehensive bootcamp', 'Web Development', 'course', 'https://example.com/web-bootcamp', true, 'beginner', ARRAY['HTML', 'CSS', 'JavaScript', 'React', 'Node.js'], ARRAY['frontend', 'backend', 'fullstack']),
('550e8400-e29b-41d4-a716-446655440002', 'Data Structures & Algorithms Master Class', 'Master DSA concepts with 300+ coding problems and detailed explanations', 'Computer Science', 'course', 'https://example.com/dsa-course', true, 'intermediate', ARRAY['Arrays', 'LinkedLists', 'Trees', 'Graphs', 'Dynamic Programming'], ARRAY['algorithms', 'coding', 'interview']),
('550e8400-e29b-41d4-a716-446655440003', 'React Cheat Sheet', 'Quick reference guide for React hooks, components, and best practices', 'Web Development', 'cheat_sheet', 'https://example.com/react-cheatsheet', false, 'intermediate', ARRAY['Hooks', 'Components', 'State Management'], ARRAY['react', 'frontend', 'reference']),
('550e8400-e29b-41d4-a716-446655440004', 'VS Code Extensions Pack', 'Essential VS Code extensions for productive development', 'Tools', 'tool', 'https://example.com/vscode-extensions', false, 'beginner', ARRAY['Extensions', 'Themes', 'Snippets'], ARRAY['productivity', 'editor', 'tools']);

-- Insert sample roadmaps with proper UUIDs
INSERT INTO public.roadmaps (id, title, description, difficulty, duration, featured, roadmap_url, download_url, technologies, tags) VALUES
('660e8400-e29b-41d4-a716-446655440001', 'Frontend Developer Roadmap 2024', 'Complete path to becoming a frontend developer with modern technologies', 'beginner', '6-12 months', true, 'https://roadmap.sh/frontend', 'https://example.com/frontend-roadmap.pdf', ARRAY['HTML', 'CSS', 'JavaScript', 'React', 'TypeScript', 'Webpack'], ARRAY['frontend', 'web', 'beginner']),
('660e8400-e29b-41d4-a716-446655440002', 'Backend Developer Roadmap', 'Master server-side development with Node.js, databases, and APIs', 'intermediate', '8-15 months', true, 'https://roadmap.sh/backend', 'https://example.com/backend-roadmap.pdf', ARRAY['Node.js', 'Express', 'MongoDB', 'PostgreSQL', 'Docker', 'AWS'], ARRAY['backend', 'server', 'apis']),
('660e8400-e29b-41d4-a716-446655440003', 'DevOps Engineer Path', 'Learn containerization, CI/CD, cloud platforms, and infrastructure management', 'advanced', '12-18 months', false, 'https://roadmap.sh/devops', null, ARRAY['Docker', 'Kubernetes', 'AWS', 'Terraform', 'Jenkins', 'Monitoring'], ARRAY['devops', 'cloud', 'infrastructure']),
('660e8400-e29b-41d4-a716-446655440004', 'Machine Learning Engineer Track', 'From Python basics to advanced ML algorithms and deployment', 'expert', '15-24 months', false, 'https://roadmap.sh/ai-data-scientist', 'https://example.com/ml-roadmap.pdf', ARRAY['Python', 'TensorFlow', 'PyTorch', 'Scikit-learn', 'Pandas', 'NumPy'], ARRAY['ai', 'ml', 'python', 'data-science']);